### PR TITLE
ci: add github-based python static analysis

### PR DESCRIPTION
**Pull request by asgardkm**
Add the following GitHub CI actions for the repository's python files:
 - python lint (`pylint`)
 - python code style check (`flake8`)
 - python security scan (`bandit`)

Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>

### CODE REVIEW

**Comment by michelleyho** [comment]
just to confirm... these analysis scans run on a per commit basis?

**Comment by asgardkm** [comment]
@michelleyho to minimize the number of CI scans, the current trigger rules in the yml file is to run the python based CI whenever a python file is modified (or whenever the github .yml file is modified).

I can add a rule to run the action on either every push to master and/or an ad-hoc basis (i.e. add a `workflow_dispatch` trigger) to the CI if desired.

**Comment by michelleyho** [comment]
that's fine.  just wanted to know the frequency of the scans.

**Review by michelleyho — DISMISSED** [review]

**Comment by michael-adler** [comment]
Can we set the Python style to enforce a wider line width, please? I haven't had any need recently to map Python to punchcards and the 80 column limit often forces really silly code transformations, especially in print statements.

**Comment by asgardkm** [comment]
@michael-adler I have no objects to increasing a wider line width. Having to wrangle one or two characters by wrapping a new line, mangling indents, shortening explicit variable names or creating temporary variables, etc, doesn't improve code quality.

I think a general rule of thumb of "90-ish" characters per line is reasonable, as explained by Raymond Hettinger, a Python core developer: https://www.youtube.com/watch?v=wf-BqAjZb8M&feature=youtu.be&t=260

Other Python related codestyle libraries land in a similar ballpark (`black` uses an 88 character line width as their rule - https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=line%20length#line-length)

However, unless involved in something like long unit test class objects, if a line is exceedingly much longer than that, then (in my opinion) something "smells" (e.g. there's likely too much logic going on in one line) and it should be re-examined.

Unless you think otherwise, I can add the a linting limit to 88 characters. Outliers can be reviewed from there to determine whether a small incrementation is necessary, or whether this is an appropriate limit for the current codebase.

**Comment by michael-adler** [comment]
It's really only strings I care about. There are plenty of cases where forcing string wrapping makes the code worse instead of better and I find myself struggling pointlessly to get strings to conform sometimes. Is there a separate configuration for strings vs. logic? You argument for 88-95 or so makes sense for logic.

Alternatively, is there some tag that can go in source to say ignore this line length? There are cases, e.g. a here document with formatting required by some other program, where Python's coding conventions shouldn't apply.

**Comment by asgardkm** [comment]
I see. For specific cases where the line length limit is deemed not applicable (e.g. strings formatted for external tool consumption), in-line exceptions can be added at the end of the line with ` # noqa: 0501`.

https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

**Comment by michael-adler** [comment]
That wouldn't work in a multi-line here document.

**Comment by asgardkm** [comment]
@michael-adler could you provide an example?

If multiple lines are too long:
  - Workaround: if multiple lines are already in place, continue to break said multiple line string into smaller strings.
  - Workaround: put lines into one big one and provide a `# noqa` exception.

However, these are suboptimal solutions. Without seeing the example, this "smells" to me.

If so much text is being hardcoded into a python script as strings (like enough for a document), one approach would be to extract the "input" text from the python script and store it in a separate text/configuration file. If variables populate the string, the string(s) in the file can be rendered as a jinja template (https://jinja.palletsprojects.com/en/2.11.x/)

Also, I don't know whether different lint rules can be set for strings/logic.

**Comment by michael-adler** [comment]
Here's an example where it would be simply stupid to have to break up the Python in order to conform to arbitrary line width. Obfuscating the Python code with extra documents or breaking up the JSON so it is no longer clearly mapping 1:1 to output text are obviously worse than violating the line width. It's Python code that is generating a JSON file:

```Python
    jf.write(''',

      {
        "class": "cci-p",
        "interface": "struct",
        "params":
          {
''')

    if (vc_supported):
        jf.write('            "vc-supported": "{}",'.format(vc_supported))

    jf.write('''
            "c0-supported-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_C0_SUPPORTED_REQS",
            "c1-supported-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_C1_SUPPORTED_REQS",
            "cl-len-supported": "`OFS_PLAT_PARAM_HOST_CHAN_CL_LEN_SUPPORTED",
            "byte-en-supported": "`OFS_PLAT_PARAM_HOST_CHAN_BYTE_EN_SUPPORTED",
            "max-bw-active-lines-c0": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_BW_ACTIVE_LINES_C0",
            "max-bw-active-lines-c1": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_BW_ACTIVE_LINES_C1",
            "max-outstanding-mmio-rd-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_OUTSTANDING_MMIO_RD_REQS",
            "suggested-timing-reg-stages": "`OFS_PLAT_PARAM_HOST_CHAN_SUGGESTED_TIMING_REG_STAGES"
          }
      }''')
```

**Comment by asgardkm** [comment]
@michael-adler thanks for the example - found fil in question here https://github.com/OPAE/ofs-platform-afu-bbb/blob/master/plat_if_develop/ofs_plat_if/scripts/gen_ofs_plat_json).

---

(My 2 cents on looking over the example - they're out of scope for this PR)

I agree that a template here isn't the best solution. It could be used to clearly show the structure of the expected JSON output (instead of going though the script's function logic to determine what string blocks go where), but it doesn't do away with managing JSON syntax via strings.
For generating a JSON file, I would define the contents of your payload as a python dictionary.
- The `json` library will automagically render the syntax for you based on the structure of your dictionary.
- This spares you the headache of manually managing string whitespace, curly brackets, stray commas, etc.
- Managing a Python dictionary is more straightforward than managing multi-line strings.

Either way, also having a function that verifies that the generated JSON file is syntactically valid would be a nice sanity check.

---

Regardless of the dictionary or string approach to generate the JSON file, given the length of the contents themselves, some exceptions are still needed.

I did a quick test on the file, and I found out that adding ` # noqa: 501` at the end of the entire `jf.write` command absolves all the line width issues in the multi-line string definition. Therefore, the following would serve the multi-line case.

```
    jf.write(''',

      {
        "class": "cci-p",
        "interface": "struct",
        "params":
          {
''')

    if (vc_supported):
        jf.write('            "vc-supported": "{}",'.format(vc_supported))

    jf.write('''
            "c0-supported-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_C0_SUPPORTED_REQS",
            "c1-supported-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_C1_SUPPORTED_REQS",
            "cl-len-supported": "`OFS_PLAT_PARAM_HOST_CHAN_CL_LEN_SUPPORTED",
            "byte-en-supported": "`OFS_PLAT_PARAM_HOST_CHAN_BYTE_EN_SUPPORTED",
            "max-bw-active-lines-c0": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_BW_ACTIVE_LINES_C0",
            "max-bw-active-lines-c1": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_BW_ACTIVE_LINES_C1",
            "max-outstanding-mmio-rd-reqs": "`OFS_PLAT_PARAM_HOST_CHAN_MAX_OUTSTANDING_MMIO_RD_REQS",
            "suggested-timing-reg-stages": "`OFS_PLAT_PARAM_HOST_CHAN_SUGGESTED_TIMING_REG_STAGES"
          }
      }''')  # noqa: E501
```

**Comment by michael-adler** [comment]
That works for me. You too, I assume.

**Review by michael-adler — APPROVED** [review]

**Pull request merged**
