### PR TITLE
Fix mmu_monitor compatibility with kernel versions 4.19.0 to 5.3.0

### PR DESCRIPTION
**Pull request by ddcc**

### CODE REVIEW

**Comment by michael-adler** [comment]
Thank you!

How did you test to confirm that events are detected correctly in the 3 kernel variants?

**Comment by ddcc** [comment]
At this point, I've just managed to build the driver and load it on a Ubuntu 19.10 machine with a 5.3.0-29-generic kernel. I'm in the process of running some tests with our benchmark applications, but they may not actually trigger changes in MMU page mappings.

**Comment by michael-adler** [comment]
You could run the test in the subdirectory below mmu_monitor. On pre-4.19 kernels it looks like this:
```
API version: 2
page_vma_info: buffer 0, va 0x7f20468bf000, ret 0 (0), page shift 12, read 1, write 1
page_vma_info: buffer 1, va 0x7f20468bd000, ret 0 (0), page shift 12, read 1, write 0
page_vma_info: buffer 2, va 0x2aaaaac00000, ret 0 (0), page shift 21, read 1, write 1
page_vma_info: buffer 3, va 0x2aaaab000000, ret 0 (0), page shift 21, read 1, write 0
page_vma_info: buffer 4, va 0x2aaac0000000, ret 0 (0), page shift 30, read 1, write 1
page_vma_info: buffer 5, va 0x2aab40000000, ret 0 (0), page shift 30, read 1, write 0
page_vma_info: buffer 6, va 0x7f20468bc000, ret -1 (12), page shift 0, read 0, write 0
munmap buffer 0, va 0x7f20468bf000
munmap buffer 1, va 0x7f20468bd000
munmap buffer 2, va 0x2aaaaac00000
munmap buffer 3, va 0x2aaaab000000
munmap buffer 4, va 0x2aaac0000000
munmap buffer 5, va 0x2aab40000000
mon_event[0] start = 0x7f20468bf000, end = 0x7f20468c1000, len = 8192
mon_event[1] start = 0x7f20468bd000, end = 0x7f20468bf000, len = 8192
mon_event[2] start = 0x2aaaaac00000, end = 0x2aaaab000000, len = 4194304
mon_event[3] start = 0x2aaaaac00000, end = 0x2aaaab000000, len = 4194304
mon_event[4] start = 0x2aaaab000000, end = 0x2aaaab400000, len = 4194304
mon_event[5] start = 0x2aaaab000000, end = 0x2aaaab400000, len = 4194304
mon_event[0] start = 0x2aaac0000000, end = 0x2aab40000000, len = 2147483648
waiting...
mon_event[1] start = 0x2aaac0000000, end = 0x2aab40000000, len = 2147483648
mon_event[2] start = 0x2aab40000000, end = 0x2aabc0000000, len = 2147483648
mon_event[3] start = 0x2aab40000000, end = 0x2aabc0000000, len = 2147483648
mon_event[0] start = 0x7f20458b6000, end = 0x7f20458b8000, len = 8192
mon_event[0] start = 0x7f204686d000, end = 0x7f2046896000, len = 167936

```

It isn't testing that every event registers, but it will give you a rough idea of whether the new code works.

**Comment by ddcc** [comment]
It works, I just needed to reconfigue and reboot the system since I didn't have enough hugepages allocated. I also had to make some changes to the test program; namely, adding the MAP_HUGE_2MB argument for 2MB hugepages, otherwise mmap() would return -EINVAL. Here's the output:

```
API version: 2
page_vma_info: buffer 0, va 0x7efefc8d8000, ret 0 (0), page shift 12, read 1, write 1
page_vma_info: buffer 1, va 0x7efefc8d6000, ret 0 (0), page shift 12, read 1, write 0
page_vma_info: buffer 2, va 0x7efefba00000, ret 0 (0), page shift 21, read 1, write 1
page_vma_info: buffer 3, va 0x7efefb600000, ret 0 (0), page shift 21, read 1, write 0
page_vma_info: buffer 4, va 0x7efe40000000, ret 0 (0), page shift 30, read 1, write 1
page_vma_info: buffer 5, va 0x7efdc0000000, ret 0 (0), page shift 30, read 1, write 0
page_vma_info: buffer 6, va 0x7efefc905000, ret -1 (12), page shift 0, read 0, write 0
mon_event[0] start = 0x7efefc905000, end = 0x7efefc906000, len = 4096
munmap buffer 0, va 0x7efefc8d8000
munmap buffer 1, va 0x7efefc8d6000
munmap buffer 2, va 0x7efefba00000
munmap buffer 3, va 0x7efefb600000
munmap buffer 4, va 0x7efe40000000
munmap buffer 5, va 0x7efdc0000000
mon_event[0] start = 0x7efefc8d8000, end = 0x7efefc8da000, len = 8192
mon_event[1] start = 0x7efefc8d6000, end = 0x7efefc8d8000, len = 8192
mon_event[2] start = 0x7efefba00000, end = 0x7efefbe00000, len = 4194304
mon_event[3] start = 0x7efefba00000, end = 0x7efefbe00000, len = 4194304
mon_event[4] start = 0x7efefb600000, end = 0x7efefba00000, len = 4194304
mon_event[5] start = 0x7efefb600000, end = 0x7efefba00000, len = 4194304
mon_event[6] start = 0x7efe40000000, end = 0x7efec0000000, len = 2147483648
mon_event[7] start = 0x7efe40000000, end = 0x7efec0000000, len = 2147483648
mon_event[8] start = 0x7efdc0000000, end = 0x7efe40000000, len = 2147483648
mon_event[9] start = 0x7efdc0000000, end = 0x7efe40000000, len = 2147483648
mon_event[0] start = 0x7efefbe8f000, end = 0x7efefbea0000, len = 69632
mon_event[0] start = 0x7efefbea0000, end = 0x7efefbea4000, len = 16384
mon_event[1] start = 0x7efefbea4000, end = 0x7efefbea6000, len = 8192
```

**Pull request merged**
